# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=out-of-process
kotlin.compiler.max.parallel.threads=1
org.gradle.configuration-cache=false
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=true
org.gradle.java.home=d:/SmartContractAI/.jdk/jdk-17.0.14+7
GEMINI_API_KEY=YOUR_GEMINI_API_KEY